routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\SizeController;
use App\Http\Controllers\UnitController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\WelcomeController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

// Route::get('/dashboard', function () {
//     return view('dashboard');
// })->middleware(['auth'])->name('dashboard');

require __DIR__.'/auth.php';

Route::middleware('auth')->group(function (){

    Route::get('/home', function(){
        return view('backend.home');
    });
    
    
    Route::get('/trashed-products', [ProductController::class, 'trash'])->name('products.trashed');
    
    Route::get('/trashed-products/{product}/restore', [ProductController::class, 'restore'])->name('products.restore');
    
    Route::delete('/trashed-products/{product}/delete', [ProductController::class, 'delete'])->name('products.delete');
    
    Route::resource('products', ProductController::class);
   
   
   
   
    Route::resource('roles', RoleController::class);
    // Route::get('/roles', [RoleController::class, 'index'])->name('roles.index');
    
    
    
    
    Route::get('/categories', [CategoryController::class, 'index'])->name('categories.index');
    
    Route::get('/categories/create', [CategoryController::class, 'create'])->name('categories.create');
    
    Route::post('/categories', [CategoryController::class, 'store'])->name('categories.store');
    
    Route::get('/categories/{category}', [CategoryController::class, 'show'])->name('categories.show');
    
    // GET	/photos/{photo}/edit	edit	photos.edit
    Route::get('/categories/{category}/edit', [CategoryController::class, 'edit'])->name('categories.edit');
    
    // PUT/PATCH	/photos/{photo} update	photos.update
    Route::patch('/categories/{category}', [CategoryController::class, 'update'])->name('categories.update');
    
    // DELETE	/photos/{photo}	destroy	photos.destroy
    Route::delete('/categories/{category}', [CategoryController::class, 'destroy'])->name('categories.destroy');
    
    
    
    
    
    
    Route::get('/sizes', [SizeController::class, 'index'])->name('sizes.index');
    
    Route::get('/sizes/create', [SizeController::class, 'create'])->name('sizes.create');
    
    Route::post('/sizes', [SizeController::class, 'store'])->name('sizes.store');
    
    Route::get('/sizes/{size}', [SizeController::class, 'show'])->name('sizes.show');
    
    // GET	/photos/{photo}/edit	edit	photos.edit
    Route::get('/sizes/{size}/edit', [SizeController::class, 'edit'])->name('sizes.edit');
    
    // PUT/PATCH	/photos/{photo} update	photos.update
    Route::patch('/sizes/{size}', [SizeController::class, 'update'])->name('sizes.update');
    
    // DELETE	/photos/{photo}	destroy	photos.destroy
    Route::delete('/sizes/{size}', [SizeController::class, 'destroy'])->name('sizes.destroy');
    
    
    
    
    
    Route::get('/units', [UnitController::class, 'index'])->name('units.index');
    
    Route::get('/units/create', [UnitController::class, 'create'])->name('units.create');
    
    Route::post('/units', [UnitController::class, 'store'])->name('units.store');
    
    Route::get('/units/{unit}', [UnitController::class, 'show'])->name('units.show');
    
    // GET	/photos/{photo}/edit	edit	photos.edit
    Route::get('/units/{unit}/edit', [UnitController::class, 'edit'])->name('units.edit');
    
    // PUT/PATCH	/photos/{photo} update	photos.update
    Route::patch('/units/{unit}', [UnitController::class, 'update'])->name('units.update');
    
    // DELETE	/photos/{photo}	destroy	photos.destroy
    Route::delete('/units/{unit}', [UnitController::class, 'destroy'])->name('units.destroy');
    

});

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    use HasFactory;
    
    protected $fillable = [
        'title'
    ];
    
    public function products()
    {
        return $this->hasMany(Product::class);
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Models\Category;
use Doctrine\DBAL\Query\QueryException;
use Illuminate\Http\Request;

class CategoryController extends Controller
{  
    public function index()
    {
        $categoriesCollection = Category::latest();
        if(request('search')){
            $categories = Category::latest()
                                ->where('description', 'like', '%'.request('search').'%')
                                ->where('title', 'like', '%'.request('search').'%');
        }
        $categories = $categoriesCollection->paginate(10);

        return view('backend.categories.index', [
            'categories' => $categories 
        ]);
    }

    public function create()
    {
        $this->authorize('create-category');

        return view('backend.categories.create');
    }

    public function store(Request $request)
    {
        // dd(request()->description);
        try{
            request()->validate([
                'title' => 'required|min:3|max:50'
            ]);
    
            Category::create([
                'title' => request()->title
            ]);
            // $request->session()->flash('message', 'Task was successful!');
            return redirect()->route('categories.index')->withMessage('Task was successful!');
    

        }catch (QueryException $e) {
            return redirect()-> back()-> withInput()-> withErrors($e-> getMessage());
            dd($e-> getMessage());
        }
        
    }

    // public function show($id)
    // {
    //     $category = Category::findOrfail($id);
    //     dd ($category);
    // }
    public function show(Category $category)
    {

        return view('backend.categories.show', compact('category'));
    }
    public function edit(Category $category)
    {
        return view('backend.categories.edit', [
            'category' => $category
        ]);
    }

    public function update(Request $request, Category $category)
    {
        try {
            $request->validate([
                'title' => 'required|min:3|max:50|unique:categories,title,'.$category->id,
                'description' => ['required', 'min:10'],
            ]);

            $category->update([
                'title' => $request->title,
                'description' => $request->description,
            ]);

            // $request->session()->flash('message', 'Task was successful!');
            return redirect()->route('categories.index')->withMessage('Successfully Updated!');
        } catch (QueryException $e) {
            return redirect()->back()->withInput()->withErrors($e->getMessage());
            // dd($e->getMessage());
        }
    }

    public function destroy(Category $category)
    {
        try {
            $category->delete();
            return redirect()->route('categories.index')->withMessage('Successfully Deleted!');
        } catch (QueryException $e) {
            return redirect()->back()->withInput()->withErrors($e->getMessage());
            // dd($e->getMessage());
        }
    }



}

resources/views/backend/categories/create.blade.php
<x-backend.layouts.master>
    <x-slot name="pageTitle">
        Add Form
    </x-slot>

    <x-slot name='breadCrumb'>
        <x-backend.layouts.elements.breadcrumb>
            <x-slot name="pageHeader"> Table </x-slot>

            <li class="breadcrumb-item"><a href="index.html">Dashboard</a></li>
            <li class="breadcrumb-item active">Add New</li>

        </x-backend.layouts.elements.breadcrumb>
    </x-slot>


    <div class="card shadow-lg border-0 rounded-lg mt-5">
        <div class="card-header">
        <i class="fas fa-table me-1"></i>
            Create Category <a class="btn btn-sm btn-info" href="{{ route('categories.index') }}">List</a>
        </div>
        <div class="card-body">

            @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
            @endif

            <form action="{{ route('categories.store') }}" method="post">
                @csrf
                <x-backend.form.input name="title"/>                
                
                <x-backend.form.button>Save</x-backend.form.button>
            </form>
        </div>
    </div>


</x-backend.layouts.master>

resources/views/backend/categories/edit.blade.php
<x-backend.layouts.master>
    <x-slot name="pageTitle">
        Edit Form
    </x-slot>

    <x-slot name='breadCrumb'>
        <x-backend.layouts.elements.breadcrumb>
            <x-slot name="pageHeader"> Categories </x-slot>

            <li class="breadcrumb-item"><a href="index.html">Dashboard</a></li>
            <li class="breadcrumb-item active">Edit</li>

        </x-backend.layouts.elements.breadcrumb>
    </x-slot>


    <div class="card mb-4">
        <div class="card-header">
            <i class="fas fa-table me-1"></i>
            Edit Category <a class="btn btn-sm btn-info" href="{{ route('categories.index') }}">List</a>
        </div>
        <div class="card-body">

            @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
            @endif

            <form action="{{ route('categories.update', ['category' => $category->id]) }}" method="post">
                @csrf
                @method('patch')
                <x-backend.form.input name="title" :value="$category->title" />               
                <x-backend.form.textarea name="description">
                {{ $category->description }}
                </x-backend.form.textarea>              

                <x-backend.form.button>Update</x-backend.form.button>

            </form>
        </div>
    </div>


</x-backend.layouts.master>

resources/views/backend/categories/index.blade.php
<x-backend.layouts.master>
    <x-slot name="pageTitle">
        Categories
    </x-slot>

    <x-slot name='breadCrumb'>
        <x-backend.layouts.elements.breadcrumb>
            <x-slot name="pageHeader"> Categories </x-slot>

            <li class="breadcrumb-item"><a href="index.html">Dashboard</a></li>
            <li class="breadcrumb-item active">Categories</li>

        </x-backend.layouts.elements.breadcrumb>
    </x-slot>

    <div class="card mb-4">
        <div class="card-header">
            <div class="row">
                <div class="col-9">
                    <i class="fas fa-table me-1"></i>
                    Categories 

                    @can('create-category')
                    <a class="btn btn-sm btn-info" href="{{ route('categories.create') }}">Add New</a>
                    @endcan

                </div>
                <div class="col-3">
                    <form method= "GET" action="{{ route('categories.index')}}">
                        <x-backend.form.input style="width: 200px; height: 20px" name="search" /> 
                    </form>
                </div>
            </div>
        </div>
        <div class="card-body">

            @if (session('message'))
            <div class="alert alert-success">
                <span class="close" data-dismiss="alert">&times;</span>
                <strong>{{ session('message') }}.</strong>
            </div>
            @endif

            <table class="table">
                <thead>
                    <tr>
                        <th class="col-1">Sl#</th>
                        <th class="col-2">Category Name</th>
                        <th class="col-7">Product-List</th>
                        <th class="col-2">Action</th>
                    </tr>
                </thead>
                <tbody>
                    @php $sl=0 @endphp
                    @foreach ($categories as $category)
                    <tr>
                        <td>{{ ++$sl }}</td>
                        <td>{{ $category->title }}</td>
                        <td><a class="btn btn-info btn-sm" href="{{ route('categories.show', ['category' => $category->id]) }}" >Show Products</a></td>
                        <td>

                            <a class="btn btn-warning btn-sm" href="{{ route('categories.edit', ['category' => $category->id]) }}" >Edit</a>

                            <form style="display:inline" action="{{ route('categories.destroy', ['category' => $category->id]) }}" method="post">
                                @csrf
                                @method('delete')
                                
                                <button onclick="return confirm('Are you sure want to delete ?')" class="btn btn-sm btn-danger" type="submit">Delete</button>
                            </form>

                            <!-- <a href="{{ route('categories.destroy', ['category' => $category->id]) }}" >Delete</a> -->


                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
            {{ $categories-> links() }}
        </div>
    </div>

</x-backend.layouts.master>

resources/views/backend/categories/show.blade.php
<x-backend.layouts.master>
    <x-slot name="pageTitle">
        Details
    </x-slot>

    <x-slot name='breadCrumb'>
        <x-backend.layouts.elements.breadcrumb>
            <x-slot name="pageHeader"> Categories </x-slot>

            <li class="breadcrumb-item"><a href="index.html">Dashboard</a></li>
            <li class="breadcrumb-item active">Add New</li>

        </x-backend.layouts.elements.breadcrumb>
    </x-slot>

    <div class="card mb-4">
        <div class="card-header">
            <i class="fas fa-table me-1"></i>
           Category Details <a class="btn btn-sm btn-info" href="{{ route('categories.index') }}">List</a>
        </div>
        <div class="card-body">
            <h3>Category Name: {{ $category->title }}</h3>
            
            <table class="table">
                <thead>
                    <tr>
                        <th>SL#</th>
                        <th>Name</th>
                        <th>Description</th>
                        <th>Action</th>
                    </tr>
                </thead>

                <tbody>
                    @forelse ($category->products as $product)
                    <tr>
                        <td>{{ $loop->iteration }}</td>
                        <td>{{ $product->title }}</td>
                        <td>{{ $product->description }}</td>
                        <td>
                            <a class="btn btn-info btn-sm" href="{{ route('products.show', ['product' => $product->id]) }}" >Show</a>
                        </td>
                    </tr>
                    @empty
                    <tr>
                        <td colspan='3' class="text-center">No Data Available</td>
                    </tr>
                    @endforelse
                </tbody>

            </table>

        </div>
    </div>

</x-backend.layouts.master>